// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadRestoreParams = { threadId: string, 
/**
 * The number of turns to restore from the end of the thread. Must be >= 1.
 */
numTurns: number, 
/**
 * When true, restore workspace files to the snapshot captured for the
 * earliest restored turn. When false, only thread history is restored.
 */
restoreFiles: boolean, };
